# Generated by Django 4.2.5 on 2023-10-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_order_items_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrption',
            new_name='description',
        ),
    ]
