# Generated by Django 4.2.5 on 2023-10-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firstname_lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
