# Generated by Django 4.2.5 on 2023-10-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile_firstname_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentDue',
            field=models.DateTimeField(null=True),
        ),
    ]
